Fix django settings for jobs
This was causing:

    ModuleNotFoundError: No module named 'ecommerce.settings.tutor'

See https://discuss.overhang.io/t/error-during-new-setup-no-module-named-ecommerce-settings-tutor/681